### ISSUE TITLE
Upload CodeSystems

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#4]
## Related to
#1 

## Description
_(Temporary copy/paste from my personal notes:)_

```
Upload CodeSystems
- what
  - loinc
  - snomed-ct
  - icd10-cm
  - rxnorm
- how
  - a. HAPI-FHIR-CLI
    - RxNorm?
    - Failed cases
    - Success cases
  - b. automation
    - Athena CSVs -> FHIR JSON
```

**Comment by joeflack4** [comment]
Davera cautioned me against using Athena OHDSI OMOP CSVs as our source vocabularies. This is because it is lossy. There are changes they made and not all information from source vocabularies are there.

**Comment by joeflack4** [comment]
For reference, I was able to use the `hapi-fhir-cli` to upload ICD10CM. But not for LOINC and SNOMED.

SNOMED
```
make upload-snomed
hapi-fhir-cli upload-terminology -d ./data/terminologies/SNOMED/SnomedCT_USEditionRF2_PRODUCTION_20210901T120000Z.zip -v r4 -t http://20.119.216.32:8080/fhir -u http://snomed.info/sct
------------------------------------------------------------
🔥  HAPI FHIR 5.6.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 85779@EB-IM-R0KHMD6R.local
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 17.0.1
------------------------------------------------------------
2022-02-16 18:56:47.343 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-02-16 18:56:48.67 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./data/terminologies/SNOMED/SnomedCT_USEditionRF2_PRODUCTION_20210901T120000Z.zip
2022-02-16 18:56:49.552 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2022-02-16 18:56:51.599 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-02-16 18:56:52.388 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown file: hapi-fhir-cli3131347798514327148.zip</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Unknown file: hapi-fhir-cli3131347798514327148.zip"
  } ]
}
2022-02-16 18:56:52.391 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli3131347798514327148.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:305)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1319)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:216)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:123)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:253)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-02-16 18:56:52.392 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
make: *** [upload-snomed] Error 1


```

LOINC
```
make upload-loinc
hapi-fhir-cli upload-terminology -d ./data/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip -d /Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/terminologies/LOINC/_archive/_Full/Loinc_2.71.zip -v r4 -t http://20.119.216.32:8080/fhir -u http://loinc.org
------------------------------------------------------------
🔥  HAPI FHIR 5.6.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 85841@EB-IM-R0KHMD6R.local
Max configured JVM memory (Xmx) : 8.0GB
Detected Java version           : 17.0.1
------------------------------------------------------------
2022-02-16 18:57:08.12 [main] INFO  ca.uhn.fhir.cli.App Logging configuration set from file logback-cli-on.xml
2022-02-16 18:57:08.740 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: ./data/terminologies/LOINC/Loinc_2.71_MultiAxialHierarchy_3.5.zip
2022-02-16 18:57:08.751 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: /Users/joeflack4/projects/hapi-fhir-jpaserver-starter/data/terminologies/LOINC/_archive/_Full/Loinc_2.71.zip
2022-02-16 18:57:10.320 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2022-02-16 18:57:11.642 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2022-02-16 18:57:13.612 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown file: hapi-fhir-cli10749622764325811546.zip</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Unknown file: hapi-fhir-cli10749622764325811546.zip"
  } ]
}
2022-02-16 18:57:13.613 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli10749622764325811546.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:305)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1319)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:216)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:123)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:253)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2022-02-16 18:57:13.614 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
make: *** [upload-loinc] Error 1
```

**Comment by joeflack4** [comment]
Apparently, the ICD10CM upload didn't include concepts, for some reason: http://20.119.216.32:8080/fhir/CodeSystem/1?_format=json

```json
{
  "resourceType": "CodeSystem",
  "id": "1",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2022-02-16T23:56:06.161+00:00",
    "source": "#hoo7Oyh75NdyGFOP"
  },
  "url": "http://hl7.org/fhir/sid/icd-10-cm",
  "version": "2021",
  "name": "ICD-10-CM",
  "status": "active",
  "content": "not-present"
}
```

**Comment by joeflack4** [comment]
http://fhir.org/guides/stats/ - Terminology IG / server index. Good source of IGs and content that we might want to load into TIMS server. May include some of what we could use for this issue.

**Comment by richard1933** [comment]
these are in html code, wonder if there is a way to parse them out, i.e. http://fhir.org/guides/stats/valueset-hl7.fhir.uv.saner-allcovid19riskfactors.html seems good fix for concept set

**Comment by joeflack4** [comment]
Yeah, definitely parseable using some screen scraping. But I imagine that this ValueSet is being fetched from some FHIR endpoint.
